work_path: "./data/sources"
repo_path: "exploitdb"
clone_url: "https://github.com/offensive-security/exploitdb.git"
output_path: "./data/raw"
outfile_basename: "vul_sightings_edb"
log_path: "./log"
log_file: "repo_drill_edb.log"