work_path: "../data/sources"
repo_path: "metasploit-framework"
clone_url: https://github.com/rapid7/metasploit-framework.git
output_path: "../data/raw"
outfile_basename: "vul_sightings_metasploit"
logfile: "../log/repo_drill_metasploit.log"